In [5]:
#Question 1
import numpy as np
Array = np.empty([4,2], dtype = np.uint16) 
print("Array")
print(Array)
print("Attributes")
print("1> Array Shape: ", firstArray.shape)
print("2>. Array dimensions: ", firstArray.ndim)
print("3>. Length of each element of array in bytes: ", firstArray.itemsize)

Array
[[   0    0]
 [   1    0]
 [1500    0]
 [  64    0]]
Attributes
1> Array Shape:  (4, 2)
2>. Array dimensions:  2
3>. Length of each element of array in bytes:  2


In [4]:
#Question 2
import numpy as np
print("Array")
Array = np.arange(100, 200, 10)
Array = Array.reshape(5,2)
print (Array)

Array
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [14]:
#Question 3
import numpy as np
Array = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
nArray = Array[:,1]
print(nArray)

[22 55 88]


In [15]:
#Question 4
import numpy as np
Array = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("The specified array is:")
nArray = Array[::2, 1::2]
print(nArray)


 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


In [16]:
#Question 5
import numpy as np
a1 = np.array([[5, 6, 9], [21 ,18, 27]])
a2 = np.array([[15 ,33, 24], [4 ,7, 1]])
Array  = a1 + a2
print("Array after addition:")
print(Array)
#did not understand the square root part


Array after addition:
[[20 39 33]
 [25 25 28]]


In [26]:
#Question 6
import pandas as pd
data = pd.read_csv(r"C:\Users\Admin\Desktop\Automobile_data.csv")
data = data[['company','price']][data.price==data['price'].max()]
data


company    price
35  mercedes-benz  45400.0

In [27]:
#Question 7
import pandas as pd
data = pd.read_csv(r"C:\Users\Admin\Desktop\Automobile_data.csv")
d1 = data.groupby('company')
d2 = d1['company','price'].max()
d2

company    price
company                              
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

In [3]:
#Question 8
import pandas as pd
german = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
c1 = pd.DataFrame.from_dict(german)
japanese = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
c2 = pd.DataFrame.from_dict(japanese)
cars = pd.concat([c1, c2], keys=["Germany", "Japan"])
carsDf

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

In [5]:
#Question 9
import pandas as pd
data = pd.read_csv(r"C:\Users\Admin\Desktop\Automobile_data.csv")
cars = data.sort_values(by=['price', 'horsepower'])
cars.head(5)

index     company body-style  wheel-base  length engine-type  \
13     16   chevrolet  hatchback        88.4   141.1           l   
27     36       mazda  hatchback        93.1   159.1         ohc   
48     66      toyota  hatchback        95.7   158.7         ohc   
36     49  mitsubishi  hatchback        93.7   157.3         ohc   
28     37       mazda  hatchback        93.1   159.1         ohc   

   num-of-cylinders  horsepower  average-mileage   price  
13            three          48               47  5151.0  
27             four          68               30  5195.0  
48             four          62               35  5348.0  
36             four          68               37  5389.0  
28             four          68               31  6095.0

In [6]:
#Question 10
import pandas as pd
data = pd.read_csv(r"C:\Users\Admin\Desktop\Automobile_data.csv")
data['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
volkswagen       4
mercedes-benz    4
mitsubishi       4
jaguar           3
isuzu            3
honda            3
alfa-romero      3
chevrolet        3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64